language: swift
osx_image: xcode9.3
xcode_project: PasscodeLock.xcodeproj
xcode_scheme: PasscodeLock
script:
- set -o pipefail && xcodebuild test -project PasscodeLock.xcodeproj -scheme "PasscodeLock" -destination "platform=iOS Simulator,name=iPhone 8,OS=latest" ONLY_ACTIVE_ARCH=NO | xcpretty;
